# Publish Conda package to Anaconda.org
# https://github.com/marketplace/actions/publish-conda-package-to-anaconda-org 

name: Publish release on Anaconda.org

on:
  release:
    types: [created]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}

